
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class PenghitungKataView extends javax.swing.JFrame {

    /**
     * Creates new form PenghitungKataView
     */
    public PenghitungKataView() {
        initComponents();
        
          // Menambahkan DocumentListener ke inputTextArea untuk menghitung kata, karakter, dan kalimat secara real-time
        
        // Menambahkan DocumentListener ke jTextFieldcari untuk pencarian secara real-time
        jTextFieldcari.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                cariKata(); // Panggil metode cariKata saat teks di jTextFieldcari ditambahkan
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                cariKata(); // Panggil metode cariKata saat teks di jTextFieldcari dihapus
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                cariKata(); // Panggil metode cariKata saat teks di jTextFieldcari berubah
            }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextArea();
        btnhitung = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        kataLabel = new javax.swing.JLabel();
        karakterLabel = new javax.swing.JLabel();
        kalimatLabel = new javax.swing.JLabel();
        jTextFieldcari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        carilabel = new javax.swing.JLabel();
        btnkeluar = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("input");

        inputTextArea.setColumns(20);
        inputTextArea.setRows(5);
        jScrollPane1.setViewportView(inputTextArea);

        btnhitung.setText("Hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        kataLabel.setBackground(new java.awt.Color(255, 255, 255));
        kataLabel.setForeground(new java.awt.Color(255, 255, 255));
        kataLabel.setText("Jumlah Kata : 0");

        karakterLabel.setForeground(new java.awt.Color(255, 255, 255));
        karakterLabel.setText("Jumlah Karakter : 0");

        kalimatLabel.setForeground(new java.awt.Color(255, 255, 255));
        kalimatLabel.setText("Jumlah kalimat : 0");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cari Kata");

        carilabel.setForeground(new java.awt.Color(255, 255, 255));
        carilabel.setText("Hasil Cari Kata :");

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(kalimatLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(karakterLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addComponent(kataLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(carilabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnhitung)
                        .addGap(56, 56, 56)
                        .addComponent(btnhapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnkeluar)
                        .addGap(48, 48, 48))
                    .addComponent(jTextFieldcari))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnhitung)
                        .addComponent(btnhapus)
                        .addComponent(btnsimpan))
                    .addComponent(btnkeluar))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carilabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kataLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(karakterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kalimatLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
        String teks = inputTextArea.getText(); // Mengambil teks dari JTextArea
        kataLabel.setText("Jumlah Kata: " + hitungKata(teks)); // Menampilkan jumlah kata
        karakterLabel.setText("Jumlah Karakter: " + hitungKarakter(teks)); // Menampilkan jumlah karakter
        kalimatLabel.setText("Jumlah Kalimat: " + hitungKalimat(teks)); // Menampilkan jumlah kalimat
    
        
    }//GEN-LAST:event_btnhitungActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        // Mengosongkan inputTextArea, jTextFieldcari, dan mengatur ulang label hasil hitungan
        inputTextArea.setText("");
        jTextFieldcari.setText("");
        kataLabel.setText("Jumlah Kata: 0");
        karakterLabel.setText("Jumlah Karakter: 0");
        kalimatLabel.setText("Jumlah Kalimat: 0");
        carilabel.setText("Hasil Cari Kata :");
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        // Menutup aplikasi
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        // Menampilkan dialog untuk memilih lokasi dan nama file
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Simpan ke File");
    int userSelection = fileChooser.showSaveDialog(this);
    
    if (userSelection == JFileChooser.APPROVE_OPTION) {
        // Mendapatkan file yang dipilih
        File fileToSave = fileChooser.getSelectedFile();
        
        // Menulis teks dan hasil perhitungan ke file
        try (PrintWriter writer = new PrintWriter(new FileWriter(fileToSave))) {
            String teks = inputTextArea.getText();
            writer.println("Teks yang dimasukkan:");
            writer.println(teks);
            writer.println("\nHasil Perhitungan:");
            writer.println("Jumlah Kata: " + hitungKata(teks));
            writer.println("Jumlah Karakter: " + hitungKarakter(teks));
            writer.println("Jumlah Kalimat: " + hitungKalimat(teks));
            writer.println("==================================");
            writer.println("Hasil Cari Kata: " + carilabel.getText());
            
            JOptionPane.showMessageDialog(this, "File berhasil disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    }//GEN-LAST:event_btnsimpanActionPerformed

    // Metode untuk menghitung jumlah kata dalam teks
    private int hitungKata(String teks) {
        // Memisahkan teks berdasarkan spasi menggunakan regex "\\s+" dan menghitung panjang array hasil split
        return teks.trim().isEmpty() ? 0 : teks.trim().split("\\s+").length;
    }
    
    // Metode untuk menghitung jumlah karakter dalam teks
    private int hitungKarakter(String teks) {
        return teks.length(); // Mengembalikan jumlah karakter dalam teks
    }

    // Metode untuk menghitung jumlah kalimat dalam teks
    private int hitungKalimat(String teks) {
        // Memisahkan teks berdasarkan tanda titik, tanda seru, atau tanda tanya dan menghitung panjang array hasil split
        return teks.trim().isEmpty() ? 0 : teks.trim().split("[.!?]").length;
    }
    
    // Metode untuk menghitung jumlah kata, karakter, dan kalimat, serta menampilkannya di JLabel
    private void hitung() {
        String teks = inputTextArea.getText(); // Mengambil teks dari JTextArea
        kataLabel.setText("Jumlah Kata: " + hitungKata(teks)); // Menampilkan jumlah kata
        karakterLabel.setText("Jumlah Karakter: " + hitungKarakter(teks)); // Menampilkan jumlah karakter
        kalimatLabel.setText("Jumlah Kalimat: " + hitungKalimat(teks)); // Menampilkan jumlah kalimat
    }
    
  
   
 
    
    // Metode untuk mencari kata di inputTextArea berdasarkan input dari jTextFieldcari
    private void cariKata() {
        String teks = inputTextArea.getText().toLowerCase(); // Mengambil teks dari JTextArea
        String kataDicari = jTextFieldcari.getText().toLowerCase(); // Mengambil kata dari JTextField

        // Jika kataDicari kosong, berhenti pencarian
        if (kataDicari.isEmpty()) {
            kataLabel.setText("Jumlah Kata: " + hitungKata(teks));
            return;
        }

        int count = 0;
        int index = 0;

        // Loop untuk menghitung kemunculan kata yang dicari
        while ((index = teks.indexOf(kataDicari, index)) != -1) {
            count++;
            index += kataDicari.length();
        }

        // Menampilkan jumlah kemunculan kata yang dicari
        carilabel.setText("Kemunculan '" + kataDicari + "': " + count); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenghitungKataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenghitungKataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenghitungKataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenghitungKataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenghitungKataView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel carilabel;
    private javax.swing.JTextArea inputTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldcari;
    private javax.swing.JLabel kalimatLabel;
    private javax.swing.JLabel karakterLabel;
    private javax.swing.JLabel kataLabel;
    // End of variables declaration//GEN-END:variables
}
